import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/components/provider";
import Footer from "@/components/Footer";
// import LocalSwitcher from "@/components/LocalSwitcher";
// import "../i18n/i18n";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale}>
      <body
        className={`font-sans antialiased text-white h-screen flex flex-col justify-between`}
      >
        <Provider>
          <div className="h-fit">
            {/* <LocalSwitcher /> */}
            {children}
          </div>
        </Provider>
        <Footer />
      </body>
    </html>
  );
}
