import type { Metadata } from "next";
import "../globals.css";
import Provider from "@/components/provider";
import Footer from "@/components/Footer";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import LocaleSwitcher from "@/components/LocaleSwitcher";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  return (
    <NextIntlClientProvider messages={messages}>
      <Provider>
        <div className="h-fit">
          <LocaleSwitcher />
          {children}
        </div>
      </Provider>
      <Footer />
    </NextIntlClientProvider>
  );
}
