import type { Metadata } from "next";
import "../globals.css";
import Provider from "@/components/provider";
import Footer from "@/components/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Provider>
        <div className="h-fit">{children}</div>
      </Provider>
      <Footer />
    </div>
  );
}
